import Head from 'next/head'

//COMPONENTS
import Banner from '../components/banner/banner'

import styles from '../styles/Home.module.css'

export default function Home() {
  const handleOnBannerButtonClick = () => console.log('Banner button')

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoiseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerButtonClick}
        />
      </main>
    </div>
  )
}
;('')
